version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVICE_TYPE=web
      - DB_DSN=${DB_DSN}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - rabbitmq
    dns:
      - 8.8.8.8
          
  celery_worker:
    build: .
    environment:
      - SERVICE_TYPE=worker
      - DB_DSN=${DB_DSN}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - rabbitmq
    dns:
      - 8.8.8.8
