version: '3'
services:
  app:
    environment:
      - DB_DSN=${DB_DSN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    environment:
      - DB_DSN=${DB_DSN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0

    build: .
    command: celery -A tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
