version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVICE_TYPE=web
      - DB_DSN=...
      - RABBITMQ_URL=amqps://mromnayo:rk8_5B2utngRpocfxpVkWbSDIUcU6MXH@duck.lmq.cloudamqp.com/mromnayo    
    depends_on:
      - rabbitmq
    dns:
      - 8.8.8.8
      
  celery_worker:
    build: .
    environment:
      - SERVICE_TYPE=worker
      - DB_DSN=...
      - RABBITMQ_URL=amqps://mromnayo:rk8_5B2utngRpocfxpVkWbSDIUcU6MXH@duck.lmq.cloudamqp.com/mromnayo      
    depends_on:
      - rabbitmq
    dns:
      - 8.8.8.8
    # No 'command:' override, so it uses CMD ["/app/entrypoint.sh"]
