version: '3'
services:
  app:
    environment:
      - DB_DSN=postgresql://postgres:gUAfzAPnULbYOAvZeaOiwuKLLebutXEY@monorail.proxy.rlwy.net:24727/railway
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  celery_worker:
    environment:
      - DB_DSN=postgresql://postgres:gUAfzAPnULbYOAvZeaOiwuKLLebutXEY@monorail.proxy.rlwy.net:24727/railway
    build: .
    command: celery -A tasks.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
