app = "flask-roleplay"
primary_region = "sea"

[build]

[processes]
  web = "sh -c \"gunicorn --bind=0.0.0.0:$PORT --timeout 600 -k eventlet main:app\""
  worker = "python celery_worker.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  
[[services]]
  # Web service: handles HTTP traffic
  internal_port = 8080
  protocol = "tcp"
  processes = ["web"]
  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  # Worker service: doesn't serve HTTP but needs a port mapping
  internal_port = 9000         # Dummy internal port (unused)
  protocol = "tcp"
  processes = ["worker"]
  [[services.ports]]
    handlers = ["tcp"]
    port = 9000              # Dummy external port (unused)
