app = "flask-roleplay"
primary_region = "sea"

[build]

[processes]
  web = "sh -c \"gunicorn --bind 0.0.0.0:$${PORT:-8080} --timeout 600 -k eventlet main:app\""
  worker = "python celery_worker.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["web"]
  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  processes = ["worker"]
  # Workers typically don't need to expose ports.
