app = "flask-roleplay-worker"
[processes]
  worker = "python celery_worker.py"
[[services]]
  internal_port = 9000
  protocol = "tcp"
  processes = ["worker"]
  [services.checks]
    type = "tcp"
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
