app = 'flask-roleplay'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']   # Updated from ['app'] to ['web']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["web"]
  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  processes = ["worker"]
  # Workers typically don't need to expose ports.
