app = "flask-roleplay"
[processes]
  web = "sh -c \"gunicorn --bind 0.0.0.0:$PORT --timeout 600 -k eventlet main:app\""
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["web"]
  [[services.ports]]
    handlers = ["http"]
    port = 80
