name: Legacy embedding guard

on:
  push: {}
  pull_request: {}

jobs:
  forbid-legacy-embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run legacy embedding guard
        run: python scripts/ci/forbid_legacy_embeddings.py
