name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"     # every 6 hours
  workflow_dispatch:
    inputs:
      refactor_goal:
        description: "High‑level refactor goal"
        default: "general code health"
        required: true

jobs:
  init-db:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_DSN: ${{ secrets.DATABASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Database Initialization Script
        run: |
          python init_db_script.py
          

  repo-steward:
    runs-on: ubuntu-latest
    needs: init-db            # wait for DB init; drop if not required
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # gh CLI uses GITHUB_TOKEN automatically, but make it explicit:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"        # matches pipeline code

      # optional: cache pip to speed things up
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (lint + tests + GH CLI)
        run: |
          pip install -r requirements.txt
          pip install ruff mypy bandit pytest         # if not in requirements
          sudo apt-get -y install gh                  # gh CLI for PRs

      - name: Run Repo Steward
        run: |
          python nyx/core/repo_refactor_pipeline.py \
            "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.refactor_goal || 'general code health' }}" \
            --pr
