name: Scale Fly.io App

on:
  workflow_dispatch:  # This lets you run it manually from GitHub Actions

jobs:
  scale:
    runs-on: ubuntu-latest
    steps:
      - name: Scale web process
        uses: superfly/flyctl-action@1
        with:
          args: "scale count --process=web 1"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Scale worker process
        uses: superfly/flyctl-action@1
        with:
          args: "scale count --process=worker 1"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
