name: Scale Fly.io App

on:
  workflow_dispatch:  # Allows you to trigger this manually

jobs:
  scale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
          export PATH="$HOME/.fly/bin:$PATH"
          flyctl version


      - name: Scale web process
        run: flyctl scale count --process=web 1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Scale worker process
        run: flyctl scale count --process=worker 1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
